name: Production workflow

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js 17.x
        uses: actions/setup-node@v1
        with:
          node-version: 17.x

      - name: Install
        run: npm install

      - name: Run Tests Locally
        run: npm run test

      - name: Build
        run: npm run build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      deployments: write

    steps:
      - name: start deployment
        uses: bobheadxi/deployments@v0.4.3
        id: deployment
        with:
          step: start
          token: ${{ secrets.GITHUB_TOKEN }}
          env: production

      - uses: actions/checkout@v2
      - name: deploy
        run: vercel --prod --yes --token=${{ secrets.VERCEL_TOKEN }}

      - name: update deployment status
        uses: bobheadxi/deployments@v0.4.3
        if: always()
        with:
          step: finish
          token: ${{ secrets.GITHUB_TOKEN }}
          status: ${{ job.status }}
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
